name: ExiirEV
description: "Exiir EV Mobile App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.7.0
  easy_localization: ^3.0.7
  location: ^6.0.2
  get: ^4.6.6
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  http: ^1.2.1
  dartz: ^0.10.1
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  sizer_pro: ^2.2.0
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/lang/
    - assets/res/
 # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  image_path_android: "assets/image/ic_launcher.png"
  image_path_ios: "assets/image/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/image/ic_launcher.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/image/ic_launcher.png" # only available for Android 8.0 devices and above
  # adaptive_icon_monochrome: "assets/image/ic_launcher.png" # only available for Android 13 devices and above
  min_sdk_android: 21 
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
